export const TOKEN_TTL_MS = 30 * 24 * 60 * 60 * 1000;
/** Destructive wipe/clear password — must be set via `supabase secrets set RESET_PASSWORD=...` (no default). */
export const RESET_PASSWORD = String(Deno.env.get("RESET_PASSWORD") || "").trim();
export const HSE_INSPECTOR = "Evan Mansour";

/** True only when a non-empty secret is configured and the client sent the matching value. */
export function resetPasswordOk(body: Record<string, unknown>): boolean {
  if (!RESET_PASSWORD) return false;
  return String(body.resetPassword || "") === RESET_PASSWORD;
}

export const CIVIL_WORKER_TEAM: Record<string, string> = {
  mohammed_luqman: "wood",
  saeed_shahuth: "wood",
  shakhwan_dilshad: "wood",
  abdulsamad_sulaiaman: "wood",
  mohammed_qasim: "tiles",
  rayan_hazhar: "tiles",
  farman_ahmed: "tiles",
  sear_samad: "plumber",
  aram_majid: "plumber",
  dlawar_kamal: "plumber",
  shwan_ali: "plumber",
  halmat_abozaid: "painting",
  sardam_sardar: "painting",
};

export const ELECTRIC_WORKER_TEAM: Record<string, string> = {
  hashim_omar: "electric",
  ibrahim_sadi: "electric",
  ahmad_sadullah: "electric",
  mariwan_saeed: "electric",
  soran_ibrahim: "electric",
  darbaz_majid: "electric",
  jasim_muhammad: "electric",
  chia_mustafa: "electric",
  wrya_muhammad: "electric",
  ibrahim_muhammad: "electric",
  muhammad_hassan: "electric",
  harim_sarkawt: "electric",
};

export const SHEET_TO_TABLE: Record<string, string> = {
  Reports: "cleaning_reports",
  Tasks: "tasks",
  TaskPhotos: "task_photos",
  WeekCoverage: "week_coverage",
  TaskLog: "task_log",
  CivilIssues: "civil_issues",
  ElectricIssues: "electric_issues",
  FireIssues: "fire_issues",
  HseInspections: "hse_inspections",
  ElectricalJobs: "electrical_jobs",
  ElectricalSummary: "electrical_summaries",
  ElectricWorkerReports: "electric_worker_reports",
  CivilWorkerReports: "civil_worker_reports",
  AsaasItems: "asaas_items",
  ApplicationChecks: "application_checks",
  ApplicationCheckHistory: "application_check_history",
  CivilJobs: "civil_jobs",
  CivilSummary: "civil_summaries",
  WarehouseGoodsIssues: "warehouse_goods_issues",
  Trash: "trash",
  WorkerLocations: "worker_locations",
  WorkerPushTokens: "worker_push_tokens",
};

export const DEPT_BY_ACTION: Record<string, string> = {
  saveReport: "cleaning",
  getReports: "cleaning",
  deleteReport: "cleaning",
  saveTasks: "cleaning",
  getTasks: "cleaning",
  clearAll: "cleaning",
  setTask: "cleaning",
  resetTasks: "cleaning",
  getWeekCoverage: "cleaning",
  markTaskWeek: "cleaning",
  getRangeCoverage: "cleaning",
  getTaskPhotos: "cleaning",
  addTaskPhoto: "cleaning",
  addTaskPhotos: "cleaning",
  deleteTaskPhoto: "cleaning",
  logTask: "cleaning",
  getTaskLog: "cleaning",
  sendCleaningReminder: "cleaning",
  notifyCleaningWeekUnlock: "cleaning",
  addCivilIssue: "civil issue",
  updateCivilIssue: "civil issue",
  getCivilIssues: "civil issue",
  markCivilFixed: "civil issue",
  clearCivilIssues: "civil issue",
  deleteCivilIssue: "civil issue",
  assignCivilIssue: "civil issue",
  markCivilNotDept: "civil issue",
  restoreCivilIssue: "civil issue",
  setCivilFixDelay: "civil issue",
  reportWorkerLocation: "civil issue",
  getWorkerLocations: "civil issue",
  saveWorkerPushToken: "civil issue",
  testWorkerPush: "civil issue",
  debugWorkerPush: "civil issue",
  addElectricIssue: "electric issue",
  updateElectricIssue: "electric issue",
  getElectricIssues: "electric issue",
  markElectricFixed: "electric issue",
  clearElectricIssues: "electric issue",
  deleteElectricIssue: "electric issue",
  assignElectricIssue: "electric issue",
  markElectricNotDept: "electric issue",
  restoreElectricIssue: "electric issue",
  setElectricFixDelay: "electric issue",
  addFireIssue: "fire",
  updateFireIssue: "fire",
  getFireIssues: "fire",
  markFireFixed: "fire",
  clearFireIssues: "fire",
  deleteFireIssue: "fire",
  addHseInspection: "hse",
  updateHseInspection: "hse",
  getHseInspections: "hse",
  markHseResolved: "hse",
  clearHseInspections: "hse",
  deleteHseInspection: "hse",
  addElectricalJob: "electrical department",
  getElectricalJobs: "electrical department",
  updateElectricalJob: "electrical department",
  deleteElectricalJob: "electrical department",
  clearElectricalJobs: "electrical department",
  getElectricalSummary: "electrical department",
  saveElectricalSummary: "electrical department",
  getElectricWorkerReports: "electrical department",
  deleteElectricWorkerReport: "electrical department",
  transferElectricWorkerReport: "electrical department",
  transferElectricIssueCompletion: "electrical department",
  transferCivilIssueCompletion: "civil department",
  addElectricWorkerReport: "electric issue",
  updateElectricWorkerReportInvoice: "electric issue",
  getCivilWorkerReports: "civil department",
  deleteCivilWorkerReport: "civil department",
  transferCivilWorkerReport: "civil department",
  addCivilWorkerReport: "civil issue",
  updateCivilWorkerReportInvoice: "civil issue",
  addCivilJob: "civil department",
  getCivilJobs: "civil department",
  updateCivilJob: "civil department",
  deleteCivilJob: "civil department",
  clearCivilJobs: "civil department",
  getCivilSummary: "civil department",
  saveCivilSummary: "civil department",
  getAsaasItems: "asaas",
  addAsaasItem: "asaas",
  updateAsaasItem: "asaas",
  markAsaasReturned: "asaas",
  deleteAsaasItem: "asaas",
  clearAsaasItems: "asaas",
  getApplicationChecks: "application",
  getApplicationCheckMeta: "application",
  getApplicationCheckDetail: "application",
  updateApplicationCheck: "application",
  importApplicationChecks: "application",
  clearApplicationChecks: "application",
  getWarehouseGins: "warehouse",
  saveWarehouseGin: "warehouse",
  deleteWarehouseGin: "warehouse",
  getWarehouseTrash: "warehouse",
  restoreWarehouseTrash: "warehouse",
  purgeWarehouseTrash: "warehouse",
  clearWarehouseGins: "warehouse",
  markWarehouseGinDone: "warehouse",
  assignWarehouseGin: "warehouse",
  listWarehouseAssignees: "warehouse",
  saveWarehouseGinReceivedSig: "warehouse",
  getWarehouseLayout: "warehouse",
  saveWarehouseLayout: "warehouse",
  getWarehouseSignatures: "warehouse",
  saveWarehouseSignatures: "warehouse",
};

export const TRASH_ACTIONS: Record<string, number> = {
  getTrash: 1,
  restoreTrash: 1,
  purgeTrash: 1,
  getUiSettings: 1,
  saveUiSettings: 1,
};
